title: AP
tagline: "Andreas Philippi. Software developer, web enthusiast and HCI student."
keywords: "Andreas Philippi, software, developer, development, web, design"
baseurl: ""
assets: /assets
language: en

# Author info
author:
  name: Andreas Philippi

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Files to exclude in the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - License.md
  - Readme.md
  - dev/
